### ISSUE TITLE
2018 年，我的本命年 - 前端工作师的年终总结

### ISSUE THREAD

**Issue by biaochenxuying** [biaochenxuying/blog#19]
![](https://upload-images.jianshu.io/upload_images/12890819-90a6157a42e33d80.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 1. 前言

时间过得很快，2018 年已经接近尾声了。离开大学校园已经一年半，正式工作也一年半了。

2018 年，我的本命年，今年 24 岁，离 “而立之年” —— 30 岁， 又近了一步。今年对我而言，是人生的一个重要节点。今年是我觉得过得最快的一年，也是成长最多的一年。

##  2. 技术

作为一名代码搬运工，技术做为安身立命的本钱，今年技术上有了挺大的见长。

技术上，前端和后端都接触到当前流行的技术栈，前端方面有： vue.js 、react.js ；后端方面有：python 3 、node、express、mongodb、mysql。

但是这些应用层的知识都是次要的，学到的编程能力和编程思维才是最重要的，毕竟一门通，门门通。况且对于程序员来说，编程能力和编程思维占了 80%，其他 api 的运用只占了 20%。

### 2.1 前端

对于 vue 的相关技术栈，虽然之前也有在用，但今年是技术上达到熟练的一年，做过 公众号、pc 端管理后台、H 5 应用。经过几个的项目的锤炼，应用上应该达到了熟练程度，也学到了不少好用的技巧。

而 react 相关技术栈 ，是今年后半年学的。**学而不用，等于没学。** 所以要实战一下才行，所以做了个博客网站的项目，也就是本人现在的个人网站，并把项目源码开源在 github 上。这个过程中，也学到了一些常用的、基本的 api ，对一般的 react 项目，也能自行搭建和开发了。

今年还看完了一本书:【WebKit 技术内幕】。看的不是纸质版的，是 pdf 的电子版，对浏览器和 WebKit 也有了一丢丢深入的了解，随着时间的久远，忘得差不多了 😅。

![](https://upload-images.jianshu.io/upload_images/12890819-eddcdfc489bfc993.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 2.2 后端

python 3 和 mysql 是前半年学的，最初想着边做前端边能用 python 的，不过没找到相应的工作，最后还是做前端，现在很久没用，也忘得差不多了啦 😅。

对于 node、express、mongodb 是今年后半年学的，主要是为了快速搭建博客网站后端的。虽然还有很多要优化的地方，特别是数据的查询方面，但是最终还是搭建出来了。过程中，发现 node 比 python 好学，毕竟是用的是 javaScript 语言。

对于编程也有了一丢丢的理解。之前看到阮一峰老师的一篇文章内容，说得好有道理。他的原文是这样说的：

>在此引用一个开发者对年轻程序员的告诫：在软件开发中，技术变化如此之快，你花费了大量时间学习技术和工具，一旦这些技术被取代，你的知识将变得毫无价值，因为它们大部分都是实施的细节。

>我最近总是在想这段话，软件开发算不算是真正的知识 ？
如果它是一种真正的知识，那么理论上，我们学到的东西大部分应该不会过时，就好像微积分不会过时一样。可是实际上，我们都知道，软件开发技能有时效性，十年前学习的编程知识，十年后几乎肯定不能用于生产。那样的话，软件开发就不能算真正的知识，只是一种实施的细节。

>公司旁边有一家税务所，每天都有很多人排队交税。如果你是第一次来交税，肯定搞不清楚怎么交，交税是一门学问，必须有人教你，要带哪些证件，要填哪些表，去哪些窗口排队等等。

>我现在认为，学习编程跟学习交税是一样的，都是学习实施的细节。一旦外部环境变了，原来的实施细节就没用了。 当代编程由于层层的抽象和封装，我们已经不必接触底层真正具有通用性的知识了。大部分时候，所谓编程就是在写某个抽象层的配置。比如，网页样式就是在写 CSS 配置，你很难说这到底是真正的知识，还是像《办税指南》那样的实施细节。

>实施细节并不是知识，而是操作步骤。如果技术栈发生变更，实施细节就会毫无用处。但是，你又不能不学习它，不知道实施细节，就没法做出项目。我觉得，**程序员应该要警惕，不要落入实施细节的陷阱，不要把全部精力花在实施细节上面，然后以为自己学到了真正的知识。对待各种语言和工具，正确的态度应该是“进得去，出得来”，既要了解足够的细节，也要能够站在宏观的角度看待它，探寻底层到底是怎么实现的。**

![](https://upload-images.jianshu.io/upload_images/12890819-b94eb508c0ca9078.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##  3. 工作

今年 5 月份的时候，换了东家。

在上一家东家那里学到了很多东西，毕竟是刚毕业后工作的第一年。上一家东家的两位前端老大和另外二位后端开发，无论是技术还是做事上，对我都产生了比较大的影响，感谢。上一家东家的工作氛围还是很好的，特别怀念的是每周五一次的运动啊。

在现在的公司，也不错，也有不少学习的榜样，就少了活动与运动节目。

我一直认为一个合格的程序员，正常的工作安排，应该都是在上班时间高效的做完的，下班了就准时下班的。所以很多时候，我都是下午 5 点半 准时下班的，毕竟回去之后，想做的事还有一堆呢。

但是非正常的工作安排就不一定了，比如项目很紧。因为项目时间紧，今年试过那么几次加班修 bugger 到凌晨 3 点的，然后早上七点多起来继续的。还试过一次项目中的数据被同事误删了，要配合后端开发抢救的，抢救到接近凌晨 4 点，第二天早上 8 点多照常起来正常上班的。只能感叹一声：**修仙真棒，年轻真好！！！**

![](https://upload-images.jianshu.io/upload_images/12890819-4fc01f851bfbb7b6.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-cba645003f4b272d.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##  4. 运动

**身体是一，金钱、地位、荣誉则是零，只有有了前面的一，后面的零才会有用；反之，则都是做了无用功。**

这一年来，还是和往年一样，时不时会进行各种运动，运动的项目一般有：跑步，健身，羽毛球，骑行等。

跑步的频率大概每月平均有 3 次吧，每次一般都是 5 公里；健身大概每周 2 次；羽毛球就得看有没有合适的时机了；而骑行呢，现在是只要天气许可，下班都是骑车回去，因为比搭公交车实在是快太多了，时间宝贵啊。不间断的运动也慢慢成为了一种习惯。正因为一直有不间断的运动，所以这一年来又没有感冒过，身体还算健康。

![图一](https://upload-images.jianshu.io/upload_images/12890819-8ca625f3d0f2d12f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- 图一是 2018-07-17 到 2018-12-18 期间，所有运动的数据，以骑行为主。

![图二](https://upload-images.jianshu.io/upload_images/12890819-ffb31080be020f0b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- 图二是 2017-03-20 到 2018-07-15 期间，所有运动的数据，以跑步为主。

两图的总路程加起来，够回家两趟了 😇。

这不间断的运动，也不算什么坚持，只是觉得应该做的，又刚好是喜欢做的事情而已。一直做着就成了习惯，**能做自己喜欢的事情是一件幸福的事情**。当然，现在正值冬季，户外运动的频率要相应减少好一点。

运动带来的益处真的是没法估量，大学四年在校期间都没有生病过，只在大一寒假在家的时候，感冒了一次。近 5 年来，还有一次感冒是一年多前，刚毕业找工作的时候，被两同学轮流感冒传染，最终没能顶住。还有的益处就是保持着一个健康的身形，腹肌，胸肌都还在，只是这一年感觉肚皮比之前厚了一点了 😂。一天坐十几个小时，来程序员来说真的很伤。

**当运动成为一种习惯，终将会是受益一生的事情。**

![](https://upload-images.jianshu.io/upload_images/12890819-702a40b1ceb336d7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##  5. 额外技能

在 21 世纪， **写作、英语和编程** 估计是最有前途的技能。

### 5.1 写作

今年掌握的最有用的技能应该就是 **写作** 了，估计这个是受用一生的技能。

逐渐地，写作又成了一个爱好与习惯。**当一项技能变成爱好的时候，就能产生很巨大的能量**（就像很多人喜欢玩的王者农药）。自从写作以来，利用在学习上的时间比之前多了，学习知识的时候有了一定的深入，毕竟要写给别人看的，自己如果都不理解，别人又怎会能懂呢。

这半年时间陆续写了 30 多篇文章，其中包含读书的笔记、随笔、技术文章，有写得不怎么样的，有写的挺好的，获得多人点赞的。虽然有时会参考一下别人的文章，但还是一直鼓励原创与坚持原创。大概只有作者才能懂原创的不易。

写博客半年以来，也见到了不一样的风景。文章写的好，会有编辑找你出书；会有猎头顾问找上你，给你介绍大厂的好工作；会有好公司的团队负责人找你，想你加入他们的团队等等。这些都有遇到过，但自知现在能力还欠缺，还要不断积累与沉淀。写作是展现自己才华与能力很好的方式，当积累到一定的程度，好机会自会找上门来。

如果 30 岁之后，不想写代码了或者写不动了，还能有一个额外技能可以谋生，且这个技能还是自己的一个兴趣来的，是多么快乐的一件事。

**努力成为一个斜杠青年才是正途。**（斜杠青年：不仅指那些有着多重身份,多重收入的人。它代表的是一种全新的人生价值，核心在于多元化的人生。）

**花一样的年纪，该奋斗的年纪不要安逸，实现梦想的同时顺便赚点钱，何乐而不为？**

![](https://upload-images.jianshu.io/upload_images/12890819-6714724fbc232e48.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 5.2 做一顿好吃的

今年后半年里，还尝试自己做饭、煲粥和煲汤。虽然这些都会，但是刚出来工作后的一年里，还没做过呢。不过都很少做饭做菜，因为实在是太耗费时间了啊，还要在旁边看着。大多都是煲粥煲汤，放好各种材料就可以了，接着就是：一边玩电脑，一边等着吃就可以了，非常方便啊。

做一顿好吃的饭菜，也是一个必备的技能，毕竟 **自己动手，丰衣足食**。

![](https://upload-images.jianshu.io/upload_images/12890819-96140b8764922af4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 5.3 理财

理财 -- 人生必会技能。今年开始尝试用其他方式理财了，比如买股票，买基金，买活期产品等，虽然还一直在亏，但是都尝试一下，才知道这些东西好不好嘛。当然理财的水也很深，不是一朝一日就可学会的，需要长期研究才行。

出来社会之后，对钱的理解越来越深刻了，长大后 99% 的烦恼是因为没钱。

![](https://upload-images.jianshu.io/upload_images/12890819-7acec8dd2d041a08.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-fb37610a6367f059.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 6. 娱乐

今年大多数空闲的时间都是和电脑度过了。看电影，看电视剧，看动漫还有运动。今年看了很多动漫，热门的 3D 国漫都看过了，或者在追着看。国漫真的强势掘起了。

今年是外出游玩最少的一年了，好像没有主动去过哪里游玩，仅有的几次都是身边的朋友叫去的。其实想去的地方真的还很多。只是还没有找到合适的那个人，和其一起去。

祖国山河那么秀丽，还是得努力挣钱，去看一看。

![](https://upload-images.jianshu.io/upload_images/12890819-1c06acc234d22cfe.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 7. 期望 2019

2018 年完成的事：

- [x] 上手 react 技术栈
- [x] 上手 node 技术栈
- [x] 完成了自己的个人博客网站
- [x] 在 github 上开源了博客网站的源码
- [x] 把写作培养成了一种习惯
- [x] 运营个人公众号 【 全栈修炼 】
- [x] 不间断的运动，保持健康的体魄
- [x] 看完了一本书【WebKit 技术内幕】
- [x] 初尝其他理财方式
- [x] 做一顿好吃的

2019 的目标：

- [ ] 把个人博客网站接入到公众号里面
- [ ] 深入 vue 技术栈的原理与内在实现
- [ ] 熟练 react 和 node 技术栈，可能还要学 java。
- [ ] 学习算法与数据结构
- [ ] 英语词汇量达到 7000 
- [ ] 加大运动量，增重 5 斤
- [ ] 坚持写作，运营好公众号
- [ ] 多看书与文章（书到用时方恨少）
- [ ] 逐渐深入其他理财方式
- [ ] 培养其他技能

**当一个目标需要很长远的时间来实现时，那就将每天要做的事培养成习惯，就会变得很容易了**（比如：英语）。

现在正值冬天，天气冷，什么都不想干。最近在学英语，跟着水滴阅读看英语原著，总是想看就看，不想看就不看了，觉得每天的任务只是个任务，还没习惯。得把每天花 20 分钟看英语原著培养成习惯才行。

>最终目标是 **尽早实现个人财富自由，做自己喜欢的事情。**

我比较赞成的财务自由的解释是：**所谓的财务自由，指的是某人再也不用为了满足生活必需而出售自己的时间了。**

不是生活所迫，谁特么想努力！目标还是要有的，不然和咸鱼有什么区别 ？虽然 **努力了不一定有结果，但是不努力一定很舒服。**

> **没被生活折磨过只有两种可能，其一是有人替你扛了，其二是别着急，还没轮到你。**

![](https://upload-images.jianshu.io/upload_images/12890819-b80e851e00eb58b6.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 8. 总结

致敬将要过去的 2018 ，期望 2019。

**要么不努力，让生活选择你，随波逐流；要么自己选择生活，做自己喜欢的事。**

**无论在哪里工作，无论做什么工作，握住能掌控的生活，遇见更好的自己，便是一件特别幸运又足够幸福的事。**

**往后余生，愿你我都能，从前生活是工作，今后工作是生活。**

**时光正好，未来还有无限可能，加油！**

## 9. 最后

![](https://upload-images.jianshu.io/upload_images/12890819-f8665293cc8d0dcf.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by JoPure** [comment]
你很棒 👏

**Comment by gauseen** [comment]
同龄

**Comment by zyt-cloud** [comment]
24岁刚毕业， 懵懵懂懂的进入了Java开发，和你的24相差甚大。如今30却是一名前端开发，看到你们就给我这种老年前端一种莫名的鸭梨

**Comment by zyt-cloud** [comment]
![5UTNT2S@TRYL@VLY$~9L(5H](https://user-images.githubusercontent.com/20038812/64323456-1bb18000-cff7-11e9-98d5-98c0de93cc4b.png)

**Comment by biaochenxuying** [comment]
@zyt-cloud 

> 24岁刚毕业， 懵懵懂懂的进入了Java开发，和你的24相差甚大。如今30却是一名前端开发，看到你们就给我这种老年前端一种莫名的鸭梨

每个年龄段都有该有的烦恼，现在的我还在为 没钱、没女朋友、没房子 等事情发愁呢。

大佬不用有鸭梨，30 岁有 30 的风景，加油。

![image](https://user-images.githubusercontent.com/24362914/64348315-8da1bd80-d027-11e9-9b2d-37b4bc5a71bf.png)

**Comment by biaochenxuying** [comment]
> 同龄
@gauseen 

同龄人加油。

**Comment by IT-Highmore** [comment]
棒👍

**Comment by senior-developers** [comment]
very good! I should 向你学习！

**Comment by biaochenxuying** [comment]
> very good! I should 向你学习！

Not bad! Not bad！We should 相互学习 😉 

![](https://user-images.githubusercontent.com/24362914/66492510-1b6d3e80-eae7-11e9-91d5-355105bcf2a4.gif)

**Comment by IT-Highmore** [comment]
到现在也是毕业满一年，工作一年了！从事前端相关 + 游戏  。感觉是什么都想学，python，react 然后看了基础，没法实践 自己也就懈怠了  现在就觉得自己太菜了，啥都不会，不知道换一份工作我还会什么

**Comment by qiutian00** [comment]
学习了，非常赞同阮一峰老师的观点

**Comment by qszy1210** [comment]
一年多后仍然要说， 你真棒！能够早早的抬头的人生一定是美丽的人生。

**Comment by verymuch** [comment]
阮老师就是阮老师，赞同加一

“在软件开发中，技术变化如此之快，你花费了大量时间学习技术和工具，一旦这些技术被取代，你的知识将变得毫无价值，因为它们大部分都是实施的细节”

**Comment by WithTheSun1997** [comment]
Nice!
