### ISSUE TITLE
String之trim迷思

### ISSUE THREAD

**Issue by simon300000** [biaochenxuying/blog#46]
https://github.com/biaochenxuying/blog/blob/master/interview/fe-interview.md

```
js 中本身是没有 trim 函数的。
```

其实是有trim的吧

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by biaochenxuying** [comment]
> https://github.com/biaochenxuying/blog/blob/master/interview/fe-interview.md
> 
> ```
> js 中本身是没有 trim 函数的。
> ```
> 
> 其实是有trim的吧
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

你说的对，已经修改，谢谢大佬。
