### ISSUE TITLE
前端工程师的 2019 年年终总结 - 真香篇

### ISSUE THREAD

**Issue by biaochenxuying** [biaochenxuying/blog#54]
![2019 年终总结](https://upload-images.jianshu.io/upload_images/12890819-2f2c2cf211b17de0.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

2020 已经进入倒计时了，2019 即将过去了啊！

今天有空就写篇 2019 的年终总结吧。

讲个鬼故事：第一批 90 后马上年满 30 岁了。

## 我的财富

先来看看别人的财富：

![](https://upload-images.jianshu.io/upload_images/12890819-6a98ca4f98d7de8d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

再来看看我的：

![](https://upload-images.jianshu.io/upload_images/12890819-62305586e1e0c4b2.gif?imageMogr2/auto-orient/strip)

![](https://upload-images.jianshu.io/upload_images/12890819-943612ada40bc91c.gif?imageMogr2/auto-orient/strip)

![](https://upload-images.jianshu.io/upload_images/12890819-7acec8dd2d041a08.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我的体重

![我的体重.gif](https://upload-images.jianshu.io/upload_images/12890819-d73ff5698d6c8f36.gif?imageMogr2/auto-orient/strip)

![肥常忧伤](https://upload-images.jianshu.io/upload_images/12890819-0092c7223e20b972.jpeg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我的健身成果

你为以是这样的 ？

![](https://upload-images.jianshu.io/upload_images/12890819-d865174314619449.gif?imageMogr2/auto-orient/strip)

其实是这样的：

![我的健身成果.gif](https://upload-images.jianshu.io/upload_images/12890819-2097136cdabce699.gif?imageMogr2/auto-orient/strip)

## 我的发量

![](https://upload-images.jianshu.io/upload_images/12890819-12a5abccd390a7f4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我的感情经历

是这样的：

![](https://upload-images.jianshu.io/upload_images/12890819-236c74944a20e93b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

相信自己的眼睛，你没有看错、网络也正常。

或者是这样的：

![别人的状态，我的单身状态.gif](https://upload-images.jianshu.io/upload_images/12890819-61bd7f951a1bdfd4.gif?imageMogr2/auto-orient/strip)

这样的：

![](https://upload-images.jianshu.io/upload_images/12890819-5830b6c2b8fd3284.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

这样的：

![](https://upload-images.jianshu.io/upload_images/12890819-9659799b071e9310.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

这样的：

![](https://upload-images.jianshu.io/upload_images/12890819-031dd3ed101be1b8.gif?imageMogr2/auto-orient/strip)

甚至是这样的：

![](https://upload-images.jianshu.io/upload_images/12890819-1268bff4c44558b5.gif?imageMogr2/auto-orient/strip)

## 我的求知欲

学习使我进步，我对知识的渴望……

![](https://upload-images.jianshu.io/upload_images/12890819-2587aff825c3ab79.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-6c28f23aa5b8249f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-e9e8107d5f14a93d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我的夜生活

![](https://upload-images.jianshu.io/upload_images/12890819-2e62a8f53561b4ba.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我对生活的态度

![](https://upload-images.jianshu.io/upload_images/12890819-2a2b7acbfa41b912.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-40c96e3885010c16.gif?imageMogr2/auto-orient/strip)

## 我的生活

![](https://upload-images.jianshu.io/upload_images/12890819-8795d89b42874c12.gif?imageMogr2/auto-orient/strip)

## 残酷的现实

![](https://upload-images.jianshu.io/upload_images/12890819-5e2280c115ff4f68.gif?imageMogr2/auto-orient/strip)

## 我的养生理念

![](https://upload-images.jianshu.io/upload_images/12890819-ca5f9c5d44097fdb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-d943ced02807a654.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我的精神

![](https://upload-images.jianshu.io/upload_images/12890819-2519414d0113c63e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 我的上班状态

![](https://upload-images.jianshu.io/upload_images/12890819-8070e3a679ee7041.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![开机，开始混底薪](https://upload-images.jianshu.io/upload_images/12890819-b3de5a95fec6c3e8.gif?imageMogr2/auto-orient/strip)

## 我的下班状态

![关机，一天工资到手](https://upload-images.jianshu.io/upload_images/12890819-085384f84dcb0215.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-18b0c4eb446b685e.gif?imageMogr2/auto-orient/strip)

## 领导对我工作的指引

![都听我的](https://upload-images.jianshu.io/upload_images/12890819-ab9c4769e6b3200a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-8117c3c1decf1374.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![需求又修改了](https://upload-images.jianshu.io/upload_images/12890819-0aba62ce5ac0113a.gif?imageMogr2/auto-orient/strip)

## 我的工作

![](https://upload-images.jianshu.io/upload_images/12890819-e22d30a18a50fc43.gif?imageMogr2/auto-orient/strip)

![那么快进大厂](https://upload-images.jianshu.io/upload_images/12890819-1aba76389b354069.gif?imageMogr2/auto-orient/strip)

## 我的投资

![](https://upload-images.jianshu.io/upload_images/12890819-794ad4c8a802f80c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![投资赔了伤心吗](https://upload-images.jianshu.io/upload_images/12890819-d8da86022d94741e.gif?imageMogr2/auto-orient/strip)

## 总的来说

我的 2019 年大概是这样的

![](https://upload-images.jianshu.io/upload_images/12890819-1624120bc5a6be3e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-96140b8764922af4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-c7b8208a08c7e263.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![苦笑](https://upload-images.jianshu.io/upload_images/12890819-c354b593f14f4207.gif?imageMogr2/auto-orient/strip)

![mmp](https://upload-images.jianshu.io/upload_images/12890819-e5ff281b2d7e6a17.gif?imageMogr2/auto-orient/strip)

真是丰富而又充实的一年呢！

好啦，2019 即将过完啦，大概就是这样。

2020，请千万对我好一点啊～～

## 2020 期望

![](https://upload-images.jianshu.io/upload_images/12890819-a4bb01913a00a8d9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![被安排的明明白白](https://upload-images.jianshu.io/upload_images/12890819-251dc79351a018b5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-5bc9c3046e2cbedf.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![吃好喝好，长生不老](https://upload-images.jianshu.io/upload_images/12890819-42ebfdd9b3bb0fd2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![请用钱砸死我](https://upload-images.jianshu.io/upload_images/12890819-a8b71c7d906827d5.gif?imageMogr2/auto-orient/strip)

![](https://upload-images.jianshu.io/upload_images/12890819-f7ca5ff26ee90e9f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 最后

今年的冬天还是很冷，希望此文能博你一笑。

此处送上我的 2018 年的年终总结：[前端工程师的 2018 年总结](https://mp.weixin.qq.com/s/-FQ15AuKpeCQqgv39qekyQ)。

预告一下，**我真正的 2019 年的年终总结**，将于 2020-01-01 在我的公众号【全栈修炼】发布，敬请期待 😁。

![](https://upload-images.jianshu.io/upload_images/12890819-9b4b6803c5900d2a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by jyl549939141** [comment]
作者是一个有意思的人

**Comment by biaochenxuying** [comment]
> 作者是一个有意思的人

看来你也是哦，哈哈哈

![image](https://user-images.githubusercontent.com/24362914/72204128-809e4a80-34af-11ea-98db-3c55b1f4c755.png)

**Comment by wrrc** [comment]
hahahahahahahahahaha(ಥ _ ಥ)
