### ISSUE TITLE
程序员如何优雅的挣零花钱！这里提供 9 种思路打开你挣钱的世界

### ISSUE THREAD

**Issue by biaochenxuying** [biaochenxuying/blog#59]
![](https://upload-images.jianshu.io/upload_images/12890819-f65c9e942ab2abad.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

如何优雅而不失体面！

虽然程序员有女朋友的不多（误），但是开销往往都不小。

VPS、域名、Mac 上那一堆的收费软件、还有 Apple 每年更新的那些设备，经常都是肾不够用的节奏。

幸好作为程序员，我们有更多挣钱的姿势。

有同学该嚷了：不就是做私单嘛。

对，但是也不太对。

做私单的确是一个简单直接方式，但在我看来，私单的投入产出比很差，并不是最优的。

但既然提到了，就先说说吧。

### 1.1 按需雇用

按需雇用是近几年新兴的私单方式，开发者在业余时间直接到雇主公司驻场办公，按时薪领取报酬。这种方式省去了网络沟通的低效率，也避免了和雇主的讨价还价，适合怕麻烦的程序员。

**程序员客栈**

不太熟悉，但国内按需雇用的网站不多，写出来供大家参考。

### 1.2 远程外包

最理想的单子还是直接接海外的项目，比如 [freelancer.com](http://freelancer.com) 等网站。

一方面是因为挣的是美刀比较划算，之前看到像给 WordPress 写支付+发送注册码这种大家一个周末就能做完的项目，也可以到 200~300 美刀；另一方面是在国外接单子比较隐蔽。

常用国外网站：

- http://freelancer.com
- https://www.upwork.com/

国内也有一个软件众包平台 [CODING 码市](https://mart.coding.net) 。

码市基于云计算技术搭建的云端软件开发平台 [Coding.net](https://coding.net) 作为沟通和监管工具，快速连接开发者与需求方，旨在通过云端众包的方式提高软件交付的效率。

码市作为第三方监管平台，会对所有项目进行审核以保证项目需求的明确性，并提供付款担保，让开发者只要按时完成项目开发即可获取酬劳。

你可以 [在这里](https://mart.coding.net/codersay) 看到开发者对码市的评价。

当然，猪八戒这种站我就不多说了，不太适合专业程序员去自贬身价。

**实现网**

[实现网](http://shixian.com) 的价格也很不错，但是我强烈建议大家不要在介绍中透漏实名和真实的公司部门信息，因为这实在太高调了。

有同学说，这是我的周末时间啊，我爱怎么用就怎么用，公司还能告我怎么的？

虽然很多公司的劳动合同里边并不禁止做兼职，但在网上如此高调的干私活，简直就是在挑衅HR：「我工作不饱和」、「公司加班不够多」…

再想象下你一边和产品经理说这个需求做不完，一边自己却有时间做私单的样子。你自己要是老板也不愿提拔这样的人吧。

## 2. Side Project

比起做私单，做一个 Side Project 会更划算。

Side Project 的好处是你只需要对特定领域进行持续投入，就可以在很长时间获得收入。
这可以让你的知识都在一棵树上分支生长，从而形成良好的知识结构，而不是变成一瓶外包万金油。

思路有两种：

一种是做小而美的，针对一个细分领域开发一个功能型应用，然后放到市场上去卖；

另一种是做大而全的基础应用（想想 WordPress），方便别人在上边直接添加代码，定制成自己想要的应用。

前一种做起来比较快，但需要自己去做一些销售工作；后一种通常是开源/免费+收费模式，推广起来更简单。

有同学会说，我写的 Side Project 就是卖不掉啊。项目方向的选取的确是比较有技巧的，但简单粗暴的解决方案就是找一个现在卖得非常好、但是产品和技术却不怎样的项目，做一个只要一半价格的竞品。

比如 Mac 下有一个非常有名的写作软件，叫 Ulysses 。我试用了一下非常不错，但就是贵，283 RMB。后来看到了 Mweb ，光是免费的 Lite 版覆盖了 Ulysses 的主功能，完整版也才 98RMB，几乎没有思考就买下来了。

### 3.1 付费社群

除了 APP 外，我觉得收费群也是可以做的。

比如可以搞一个技术创业群，找一些创业成功的同学、做投资的同学、做法务的同学，面向想创业的同学开放，每人收个几百块的年费。

然后你在创业过程中遇到的问题，都可以有人解答，不会觉得是孤零零的一个人。

如果遇到了问题，群里的人可以解答；如果没遇到问题，那不是更好么。有种卖保险的感觉，哈哈哈。

比较好用的工具是 [知识星球](https://www.xiaomiquan.com) 也就是之前的小密圈。这个工具比较适合交流和讨论，长文比较痛苦。可以发布到其他地方，然后粘贴回来。

另一个靠谱的工具大概是微博的 V+ 会员。说它靠谱主要是它在微博上，所以等于整合了 「内容分发」→ 「新粉丝获取」 → 「付费用户转化」 的整个流程。

PS：交流型付费社群的一个比较难处理的事情是，很难平衡免费的粉丝和付费的社群之间的关系，所以我最后的选择是付费类的提供整块的内容，比如整理成册的小书、录制的实战视频等；而日常零碎的资料分享还是放到微博这种公开免费的平台。

### 3.2 专家平台

如果你在技术圈子里边小有名气，或者在某一个业务上特别精通，那么通过做咨询来挣钱是一种更轻松的方式。

和人在咖啡厅聊几个小时，几百上千块钱就到手了。

国内这方面的产品，我知道的有下边几个：

- [在行](http://www.zaih.com/app/): 这个是果壳旗下的，做得比较早，内容是全行业的，所以上边技术向的反而不多。
- ~~[缘创派](http://q.ycpai.com/h5/lightPartner/expertList): 缘创派的轻合伙栏目，主要面向创业者，适合喜欢感受创业氛围的技术专家们。~~
- ~~[极牛](http://geekniu.com/): 你可以认为这是一个程序员版本的「在行」，我浏览了下，虽然被约次数比在行要低不少，但专业性比较强，期望他们能尽快的推广开来吧。~~
- ~~[知加](http://get.ftqq.com/353.card)：这个项目是我参与的，面向程序员，类似「分答」的付费语音问答，刚开始内测，上边有一些硅谷科技公司的同学。感兴趣的可以看看。~~

做咨询虽然也是实名的，但和私活是完全不同的。

咨询的时间短，不会影响到正常的休息，更不会影响上班；

而且大部分公司是鼓励技术交流的，所以大家的接受度都很高。

### 4.1 投稿

很多同学喜欢写技术博客，其实把文章投给一些网站是有稿费的。

比如 InfoQ，他们家喜欢收 3000~4000 字的深度技术文章；稿费是 200 元 / 篇。

虽然不算太多，但一篇长文的稿费也够买个入门级的 Cherry 键盘了。我喜欢 InfoQ 的地方是他们的版权要求上比较宽松。
文章在他们网站发布后，你可以再发布到自己博客的；而且文章可以用于出书，只要标明原发于 InfoQ 即可。

文章还可以发到微博、微信、简书等支持打赏的平台。个人建议是换个咱程序员自己的平台写文章。

更详细的说明见这里：[https://www.infoq.cn/instruction](https://www.infoq.cn/instruction)

### 4.2 出版

顺便说一句，比起写文章，其实通过传统发行渠道出书并不怎么挣钱，我之前到手的版税是8%，如果通过网络等渠道销售，数字会更低。

出电子书收益会好一些，我之前写过一篇文章专门介绍：《[如何通过互联网出版一本小书](http://get.ftqq.com/6914.get)》

以前一直写图文为主的书，用 Markdown 非常不错；但最近开始写技术教程类的书，发现 Markdown 不太够用了，最主要的问题有 

- ① 不支持视频标签，尤其是本地视频方案 
- ② 代码高亮什么的很麻烦 
- ③ 也没有 footer note、文内说明区域的预置。

这里要向大家严重推荐 [Asciidoc](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/)，你可以把它看成一个增强版的 Markdown，预置了非常多的常用格式，而且 GitBook 直接就支持这个格式（只要把.md 搞成 .adoc 就好），Atom 也有实时预览插件。
用了一段时间，非常喜欢。

**掘金小册**

[小册](https://juejin.im/books) 是由掘金推出的付费文集产品。

我是小册的第一批作者，一路用下来还是很不错的。

文章格式直接采用 Markdown ， 发布以后可以实时更新，保证内容的新鲜度，非常的方便。

小册的一般定价在 19~29，通用内容销量好的能过千，细分内容基本也能过百。

挣零花钱的话，是个非常不错的选择。

### 4.3 付费文集

最近一年有不少的付费文集产品出现，可以把它看成传统出版的一个网络版。

一般是写作十篇以内的系列文章，定价为传统计算机书的一半到三分之一。

付费文集产品通常是独家授权，所以在选择平台方面一定要慎重，不然一个好作品可能就坑掉了。

**达人课**

[达人课](http://gitbook.cn/gitchat/columns) 是 GitChat 旗下的付费文集产品，现在应该已经合并到 CSDN 了。

GitChat 的用户群不算大，但付费意愿还可以，大概因为内容就没有免费的🤣。

之前我上课的时候是提交完成以后的文档给编辑，由编辑同学手动上架。

感觉比较麻烦，尤其是修改错别字什么的。

**小专栏**

这个平台不熟……写到这里仅供参考。

## 5. 教学视频

应聘程序教学网站讲师的经验：应聘程序教学网站讲师，出视频+作业教程，平台按小时支付，这个不知道算不算挣零花钱，我算了一下去年，一年大概出 20 个小时视频，拿到手是不到 6 万的样子，平时就是周末花时间弄下。

在线教育起来以后，录制教学视频也可以赚钱了。

关于录制在线课程的收益，一直不为广大程序员所知。但最近和 [51CTO 学院](http://edu.51cto.com/)  和  [网易云课堂](http://study.163.com/smartSpec/intro.htm#/smartSpecIntro) 的同学聊天，才发现一个优秀的 40~60 节的微专业课程，一年的收益比得上一线城市高级总监的收入。

难怪最近做培训的人这么多 😂

### 5.1 渠道和分成

大部分的平台合同有保密协议，所以不能对外讲。

但 [网易云课堂](https://study.163.com) 和 [Udemy](https://www.udemy.com/) 在公开的讲师注册协议中写明了分成，所以这里说一下。

**网易云课堂**

网易的课分三类：

- 独立上架：等于网易提供平台（视频上传管理、用户管理、支付系统等），由你自己来负责营销。这个分成比例在 9:1 ，平台收取 10% 的技术服务费。我觉得非常划算。
- 精品课：由网易帮你推广，但需要和他们签订独立的合同，会收取更多的分成。最麻烦的是，通常是独家授权。一旦签署了，就不能在其他平台上架课程了。
- 微专业：这个是网易自己规划的课程体系，从课程的策划阶段就需要和他们深度沟通。也是网易推广力度最大、收益最大的一类课程。

方糖全栈课就放在网易平台上，觉得好的地方如下：

- 支付渠道相对全，还支持花呗，这样对于我这种高价课就非常重要。苹果应用内购买课程渠道费用会被苹果扣掉 30%，好想关掉 🤣
- 自带推广系统，愿意的话可以用来做课程代理系统。

**Udemy**

相比之下 Udemy 就很贵了，分成是 5:5 ；支付上国内用户只能通过信用卡或者银行卡绑 paypal 支付。但可以把课程推向全球。（但我英文还不能讲课🙃）

腾讯课堂没用过，欢迎熟悉的同学 PR 。

### 5.2 小课和大课

我个人喜欢把视频分成小课和大课两种。

因为视频虽然看起来时间短，但实际上要做好的话，背后要消耗的时间、要投入精力还是非常多的。

大课动不动就是几十上百个课时，绝大部分上班的程序员都没有时间来录制。

所以挣零花钱更适合做小课，这种课一般就几个小时，剪辑成 10 个左右的小课时，价格在几十百来块。

如果是自己专业纯熟的领域，一个长假就可以搞定。

### 5.3 表现形式

在课程的表现形式上，我个人更喜欢 [designcode.io](http://designcode.io) 这种 图文+视频 的模式，一方面是学习者可以快速的翻阅迅速跳过自己已经学会的知识；另一方面，会多出来 微博头条文章、微信公众号、知乎和简书专栏这些长文推广渠道。

当然，内容本身才是最核心的。现在那么多的免费视频，为什么要来买你的收费版？

其实现在绝大部分教学视频，往往都真的只是教学，和现实世界我们遇到的问题截然不同。里边都是一堆简化后的假项目，为了教学而刻意设计的。

这里和大家分享一个我之前想操作的想法。

就是在自己决定开始做一个开源项目后，用录屏软件把整个过程完完整整的录下来。开源的屏幕录制工具 [OBS](https://obsproject.com/download)，1920*1080 的屏幕录成 FLV 格式，一个小时只需要 1G，一个 T 的移动硬盘可以录制上千小时，对一个中型项目来说也足够了。

等项目做完，就开源放到 GitHub，让大家先用起来。等迭代稳定后，再从录制的全量视频中剪辑出一系列的教程，整理出一系列的文章，放到网站上做收费课程。

这样做有几个好处：

 - 保证所有遇到的问题都是真实的，不是想象出来的，学习过这个课程的人，可以独立的将整个项目完整的实现。
 - 没有特意的录制过程，所以教程其实是软件开发的副产品，投入产出比更高。
 - 如果你的软件的确写得好，那么用过你软件的人可以成为你的客户或者推荐员。

### 5.4 后续

今年我录制 [方糖全栈课](https://quanzhanke.github.io/) 的时候就采用了上边这个思路，效果还不错，不过有几个小问题：

- 连续性。录着视频写代码总会有一种潜在焦虑，平时经常写一会儿休息一会儿，录像时就会留下大段的空白，有点浪费空间。当然这个主要是心理上的。
- 录音。录音的问题更大一些。因为一个长期项目很难一直处于一个安静的环境，另外基础课录制可能需要大量的讲解，几个小时写下来嗓子哑了 🤣 。
- 最后的解决方式是剪辑的时候重新配音，不过需要注意音画同步问题。

### 5.5 硬件

硬件上边，最好买一个用来支撑话筒的支架。不要用手直接握着话筒来录，这样就不会有电流声（或者很小）。

外接声卡我用的是 XOX ， 在 Mac 下边效果挺好，但不知道为啥在 Windows 上回声比较大（当然也可能是系统设置的原因）。

---

2019年的做课总结：《如何做一个日入十万的技术课程》

- [上篇：关于做课你不知道的几个事实](http://t.cn/Aie7X8b4?m=4445804259186433&u=1088413295)
- [中篇：选题、定价和预售](http://t.cn/AieySRUS?m=4446120757005290&u=1088413295)
- [下篇：大纲、内容组织和软硬件](http://t.cn/Aie5DwyW?m=4446435208406528&u=1088413295)

### 5.6 软件

如果是没有太多界面切换的课程，那可以使用 keynote 自带的录音。在其他环境里边的演示的视频可以直接粘贴到 keynote 里面来播放。

但是当你有很多的外部界面的时候，就需要录屏了。mac 上可以直接用 quicktime 来录制。文件，新建里边选 record screen 就好。

我录全栈课的时候，因为会在三个操作系统上录一些界面，所以我选择了 obs。虽然这个工具主打的是直播，但实际上它的录制功能也还是挺不错的。 

剪辑的话，用 mac 的 imovie 基本就够了，主要用到的功能就是分割片段，然后把不要的删掉。音频去下底噪。部分等待时间过长的片段加速下。当然 adobe 家的也行，就是贵。

## 6. 内部推荐和猎头推荐

如果你在 BAT 等一流互联网公司工作，如果你有一帮志同道合的程序员朋友，那么基本上每隔几个月你应该就会遇到有想换工作的同事和朋友，所以千万别错过你挣推荐费的大好时机。

一般来讲，公司内部推荐的钱会少一些，我见过的 3000~6000 的居多。
但因为是自己公司，会比较靠谱，所以风险小一些。经常给公司推荐人才，还会提升老大多你的好感度，能优先就优先吧。

比起内部推荐，猎头推荐的推荐费则会多很多。
一个 30 万年薪的程序员，成功入职后差不多可以拿到 1万RMB 的推荐费。但猎头渠道的问题在于对简历质量要求非常高，有知名公司背景的才容易成单；回款周期又特别长，一般要入职过了试用期以后才能拿到全部推荐费，得小半年。

## 7. 小结

> 工作两三年的程序员，如果不是非常非常需要钱，我还是建议先做好本职工作，把业余时间用来学习技术、深入技术，因为前几年是技术提升非常快的时期，提高技术带来的财富往往是翻倍增长的，也是这些小小的零花钱比不了的。

**天下熙熙皆为利来，天下攘攘皆为利往**，钱财所到之处，必然人头攒动、摩肩接踵。当大家躬身入局之时，定会发现存在僧多肉少的尴尬局面。

学会挣钱是一件非常重要的事情，它会让你了解商业是如何运作的，帮助你理解公司的产品逻辑、以及为你可能的技术创业打下坚实的基础。

所以我鼓励大家多去挣零花钱，最好各种姿势都试试，会有意想不到的乐趣。

本文大部分内容来自于开源项目：[程序员如何优雅的挣零花钱：https://github.com/easychen/howto-make-more-money](https://github.com/easychen/howto-make-more-money)。

笔者丰富了很多内容，并重新进行了排版优化。

## 8. 几点思维与认知

作为程序员来讲，我一直都认为：

> **技术重要吗？重要！非常重要！毕竟这毕竟是谋生的技能。但是技术以外的能力，程序员真的都应该学一学。技术一般也只能用 3 - 10 年而已，但是相比于人的一生，真的非常短。技术以外的东西，绝对能够提高一个人的高度，陷在技术里，只会让自己的思维越来越窄。**

### 8.1 技术只是一个工具

我们要深刻的认识到技术仅仅只是一个工具。当程序员是学会使用了工具，用这个工具去打工赚钱。其实，我们应该脱离出这个思维陷阱出来，学会让工具为你打工，而不是你用着这个工具去给别人打工。

举个简单例子：别人用 Python 写了一个爬虫，天天爬美女图片，然后搭建了一个美图的网站，上面放上了 Google 的广告联盟，每天爬虫工具都会定时去其他网站去爬美女图片，放到自己的网站上，而自己的网站久而久之就会很多流量进入，然后广告收入就越来越多。

所以，程序员应该学会让工具为你打工，而不是你用工具给别人打工。

### 8.2 接私活不挣钱，学会利用边际成本递减

很多程序员想：我拥有技术，我可以开发软件，我可以利用业余时间接私活挣钱。

现实情况是接私活非常累，看似自己挣钱了，其实与自己投入的时间和精力相比，你根本就没有挣钱。接过私活的同学都应该有这种感受吧？

就是大家应该开发一个软件，比如：小程序商城，你开发出来了，你这套程序员可以重复卖。你开发第一个小程序商城的成本可能是 2 万，你卖给第一个客户 5000 ，你可能感觉自己赔了，但是，你这套代码可以重复卖很多人啊，卖到第四个人的时候，收回成本，卖到第 6 个人，就是赚钱，等卖到 10 个人的时候，你哪里还会有成本呢？

这就是边际成本递减效应。大家应该学会重复利用软件的价值，可以做到软件的边际成本为 0 。

### 8.3 用钱买别人的时间是最划算的买卖

第一层境界——打工者：同一份时间，出售一次。

第二层境界——成长者：同一份时间，出售两次。

第三层境界——IP者：同一份时间，出售多次。

到了第三层境界，你发现你自己的时间价值已经到顶了，同一份时间已经出售多次了，还能怎么提升？

 第四层境界——资本家：用钱买别人的时间，创造了价值，然后再卖出去。

## 9. 最后
​
**何以解忧？唯有暴富！**

如果本文对你哪怕有一丁点帮助，可以点个赞，你的肯定是我继续写出好作品的最大动力。

​

**Comment by jvxiao** [comment]
Thank you for sharing!
