### ISSUE TITLE
前端工程师的 2020 年终总结 - 乾坤未定，你我皆黑马

### ISSUE THREAD

**Issue by biaochenxuying** [biaochenxuying/blog#79]
![](https://upload-images.jianshu.io/upload_images/12890819-a6c382d8919e7390.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

Hello，小伙伴们好呀！

又一年过去了，新年快乐呀！

极其魔幻 2020 终于都过去了，庆幸的是我们还活着，感谢那些逆行者们，感谢！

又到总结一年成长的时刻，我 2020 的关键词是：**乾坤未定，你我皆黑马**

![](https://upload-images.jianshu.io/upload_images/12890819-b93ca2ef9637ea76.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 回顾 2020 的目标

- **深入 Vue 技术栈的原理与内在实现** - 没完成

  这个没完成，因为要出 Vue3.0 了，所以没有继续学习 Vue2，但是 Vue3.0 的原码倒是学习了一点。

- **学习 Vue3、 TypeScript、Node 技术栈** - 完成

  这 3 个都有学习，Vue3 是 2021 年前端必备的技术了，还学习了 TypeScript 和 Node ，因为工作中要用到，不过没有输出文章。

- **英语词汇量达到 7000+**  - 完成 30%

  这个就惭愧了，年初报的一期英文阅读里有《寻梦环游记》和《冰雪奇缘》两部经典，《寻梦环游记》阅读了 60% 左右而已，另外一部都没开始，一部都没有完成 😢，强行推锅给工作加班 😬

- **保持运动，常锻炼** - 完成

  这应该是一直在践行并快乐着的事项了，一直有跑步和健身，今年还多了一项游泳，哈哈。

- **坚持写作** - 完成 50%

  今年只写了 12 篇原创技术文章，惭愧。还写了 14 篇前端优质项目推荐的文章。写作与运营比较佛系，读者没有大幅度增长，唉。

- **多阅读** - 完成 50%

  今年读完了几本书，在读的书有十几本，读过的书不及往年。

- **掌握摄影技术** - 完成 20%

  这个没排上日程，只看了些抖音的摄影博主发的拍摄技巧。

- **多做持续、延迟满足和有复利效应的事情** - 完成 60%

  学习、读书、写作、开源、做有影响力的事情，算是一直在践行吧。

- **做一个有作品的人！** - 完成 60%

  同上，只是开源的作品还不算特别优质。

- **暴富！暴富！暴富！** - 完成 0%

![](https://upload-images.jianshu.io/upload_images/12890819-8cade6e7259d8280.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- **等国家给我发一个女朋友！** - 完成 0%

![难受想哭](https://upload-images.jianshu.io/upload_images/12890819-178e85636eced097.gif?imageMogr2/auto-orient/strip)

所以，总的来说，去年的目标几乎都被打脸了啊 😥，还被打的好痛那种 😰。

![](https://upload-images.jianshu.io/upload_images/12890819-1ba93f3fb3582c3c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

魔幻的 2020 ，去你的，哼。

![](https://upload-images.jianshu.io/upload_images/12890819-4bdf0287762db0cb.gif?imageMogr2/auto-orient/strip)

## 工作与技术

今年的工作真的好忙、好忙、好忙！！！

今年，我做的项目是创新项目，也就是刚起步不久的项目。

本来人手还勉强能达到平衡，我是做前端项目的，就是 Vue + TypeScript 的项目的。

但是在年初的时候，一个后端大佬和一个做自动化的大佬调回原来的部门去了，所以我要接手自动化的工作，工作交接时，因为疫情的关系，还是线上远程交接的，非常被动。

自动化的项目就是用了 Puppeteer + Node 的技术栈的，所以又临时临急去学了 Puppeteer，Node 是很久之前有学过的，加上是 js ，不用花太多时间去学习。

因为自动化项目都是根据页面元素去捉取数据的，所有只要网站的元素变化了，就会出现异常，所经常周末要处理异常，也总遇到一些奇奇怪怪的问题，周末还时不时要做技术调研，研究某个方面的技术能否实现某个需求，从而减轻工作量或者实现某个业务需求。

熟悉了自动化项目后，平时除了做前端项目，还要做自动化项目，这个状态一直持续到了 12 月下询，经常都是 21 点 或者 22 点左右才下班。

今年带过 2 个前端实习生，一个正职前端，在带人上也积累了一些经验吧。

4 - 9 月的这段时间里，还没有客服团队的时候，都是所有正职的技术、产品、市场轮流做客服的，周一到周五的晚上要值班到 22：00，周六和周日是值班到 19：00，一是熟悉自己做的产品，二是人手真的不够。

所以直到 10 月份招了客服团队了，周末才有空写下文章。

比较幸运的是：做的项目起来了，3 月份从原来部门里面独立出来，成立了一个新的部门；9 月，部门独立出来成了一家公司，自负盈亏，几乎完全脱离了原来的公司。

也算做过一个成功的项目了，这个过程还是学到了很多技术之外的东西吧，如何把敏捷开发思想与目前的团队结合起来，leader 是如何做的项目管理，怎样的团队成员才有战斗力，项目做到哪个阶段可以大力推广，种子用户是如何培养起来了，项目需求的优先级是如何安排的。

---

技术方面，今年最大的收获就是增加了技术的广度，而深度方面并没有太大收获。

今年重温了一下 TypeScript，还学了 Puppeteer 的自动化或者叫爬虫技术，还有 Node.js 的熟练使用，还试了一下新出的 Vue3。

最不幸的是又多了一根白头发 😲，除了那两根白头发，剩余的三千青丝秀发如初，乌黑发亮浓密。

![](https://upload-images.jianshu.io/upload_images/12890819-3b800bbc063c0139.gif?imageMogr2/auto-orient/strip)

## GitHub

最近几年一直有在 GitHub 上为开源做贡献，今年的代码贡献相对少了好多，但是也还是取得了一点点成果。

时间可以让平凡的事情，变得不平凡。

3 年了，越来越感觉自己的技术还很弱，还有很长很长的路要走。

## 关于学习

今年最大的感触就是 **过度忙碌使你落后**。

一个人的学习热情总是有时限的，总会在一段时间过后消耗殆尽，如何平时工作过度忙碌，那么学习热情也会下降，这个时限也会缩短，太过忙碌，有空时就想娱乐一下，最终导致本来有空学习的时候不会学习了。

过度忙碌会导致没有时间学习和更新自己的知识，尤其在这个高速发展的时代。

很容易带来如下问题：

- 缺乏学习导致工作能力没有提升，而面对的问题却变得日益复杂。 
- 技术和业务上没有更大的领先优势，只能被动紧紧追赶。

反过来上面这些问题会导致你更加繁忙，进而更没有时间提高自己的技术技能，很快就形成了一个恶性循环，并最终成为井底之蛙。

今年差点就进入了那个状态了，再忙也要留一点时间给自己，充实一下自己，更新一下自己的知识库。

## 阅读

今年读过的书比上一年少了好多啊，唉 😲

![](https://upload-images.jianshu.io/upload_images/12890819-3670dd8c59bf4c88.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-2c1b2fe01ccd6d9a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

最惭愧的是英文阅读了，年初报的一期英文阅读里有《寻梦环游记》和《冰雪奇缘》两部经典，一部都没有完成 😢，强行推锅给工作加班 😰

![](https://upload-images.jianshu.io/upload_images/12890819-b0a3b708dc7f85f4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

> 昨日种种，皆成今我，切莫思量，更莫哀，从今往后，怎么收获，怎么栽。

这个世界发展的真相就是马太效应，强者越强，弱者越弱。

## 理财

投资是认知的变现。

我的理财类型应该是属于平衡型理财，我的一部分资金用来定期理财，一部分用来购买货币类产品、基金等中下风险的产品，还没有买股票，只是观望，也还没购买过高风险高收益的产品。

今年理财的收益还行吧，用于理财部分，总体收益达到了 25% 左右，还算一般般吧，收益基本都是今年基金卖出带来的收益。

我的基金基本都是以定投的形式买入的，定投了十几个基金，每个基金每周定投 2 百块左右，并设置了智能定投。

今年 2 月中旬的时候，疫情来临，我看到股市与基金都跌的那么多，我赶紧加仓了大概 1 万块，其实那时还想继续加仓的，但是毕竟是疫情，不知道影响面会有多大，所以还是要留点闲钱来应对未来更糟糕的疫情与经济危机。

今年 8 月的时候，股市和基金涨的比较凶，有的基金收益达到了 70% - 80%，所以我分批卖出了，选择了落袋为安，因为只要还没落袋，就不是你的收益。

基金的策略就是：低位时买入，攒便宜份额，定投能平摊成本，等到高位时卖出，赚取中间的收益。

买基金与股票切忌 **追涨杀跌**，而是应该 **别人恐惧时我贪婪，别人贪婪时我恐惧**。

提醒一下：**不懂的东西最好不要碰，特别是关乎钱方面，要不然很可能会成为韭菜，要碰也是学习了相关知识再去碰**。

---

**该如何确定自己的财务自由目标？**

如果大家给自己定财务目标的话，我建议可以分级制定目标（这里参考也大的建议）。

- 先根据自己的当前年度日常开支，乘以 10（以 10% 收益率为参考）作为第一个目标。
 达到这个目标后，被动收入基本可以超过日常开支。虽然还没有自由，但是你的心态已经非常不一样了。

- 再根据自己的当前年度工作收入，乘以 10（以 10% 收益率为参考） 作为第二个目标。
  达到这个目标后，被动收入可以超过工资收入，你就有了充足的炒老板的底气。

- 然后再往上就是逐层增加安全边际了。

德国有个统计，当人的年收入超过 50 万以后，收入再增加对生活幸福感的贡献就趋近于 0 了，可以作为大家的最终目标来参考。

我觉得，对于普通人来说，在没有资源，没有背景的情况下，第一桶金就显得尤为重要了，特别是第一个 100 万，因为它反映了你当前的认知与挣钱能力，还有这过程中得到的各方面的锻炼和所提升的能力。

今年看到的一句话让我感触颇深：**任何一个男孩子小时候的梦想绝对不是买套房！**

> 普通人，在没有资源，没有背景，靠知识、经验、技能的积累，再有一些耐心，才是唯一的出路。

## 健身

这一年来，还是和往年一样，时不时会进行各种运动。

- 跑步平均 3 次 / 每月，5 公里左右 / 每次
- 健身平均 1次 / 每周
- 游泳（7 - 9 月的每周四有进行）
- 骑行平均 1 次 / 每周

还有羽毛球的，因为搬办公地点时，弄丢了，就没有再玩了 😭

健身次数比之前少了啊，还好好身材还在。

不间断的运动已经成为了一种习惯，或者可以说是一项兴趣了，非常棒。

还保持着一个健康的身形，腹肌，胸肌都还在，只是这一年感觉肚皮比之前厚了一丢丢了 😂。

今年跑步最远的一次：

  ![](https://upload-images.jianshu.io/upload_images/12890819-0f25ac1d61230dc9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

还有当时的朋友圈：

![](https://upload-images.jianshu.io/upload_images/12890819-aaf25068084e8e94.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

今年跑步应该有一百多公里吧。

今年进行了一项新运动项目：游泳。

从蛙泳到自游泳，虽然还没学会自游泳，但是这个夏天值得。

![](https://upload-images.jianshu.io/upload_images/12890819-abfcfe4ba9d99b01.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

今年的小米运动的年度报告没有出来，不然可以晒一下年度运动报告的。

今年搬到江边了，不在原来的地方了，所以运动场所也发生了改变，我平时都在江边跑步了，风景也换了。

![](https://upload-images.jianshu.io/upload_images/12890819-75b40962be3756b8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-426570320fe00901.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-06d800a7b4839c12.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

还偶遇了一次小灰兔

![](https://upload-images.jianshu.io/upload_images/12890819-33dd9d66c538d2c5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 斯人若彩虹，遇上方知有

![](https://upload-images.jianshu.io/upload_images/12890819-e1473a806e9dcdd6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

今年又拒绝了三个女生，我真是一个优秀的男孩，看着她们落寞的背影，我只能默默的说声抱歉，你们的这个楼盘、保险、理财产品我是真的买不起呀，拜托，别找我了。

这么好的女生，就这样被我拒绝了，渣男！

所以，2020 年过去了，我依然散发着单身狗的清香。

![](https://upload-images.jianshu.io/upload_images/12890819-018cd3df2cc8a01e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

今年请了一天假参加了一个同学的婚礼，毕业至今，已经参加了两个同学的婚礼了。

如果今年不是请了那一天假，我都成为公司全年都全勤的人了 😂。

前端老大说的对，去年我唯一一次请假是参加别人的婚礼，今年的唯一一次请假还是参加别人的婚礼，什么时候请假是为了自己的呢 😂 

我 。。。我是一个没有感情的工具人 😭

![](https://upload-images.jianshu.io/upload_images/12890819-bd1c476211f3ee85.gif?imageMogr2/auto-orient/strip)

未来要和你共度一生的那个人，其实在与你相同的时间里，也忍受着同样的孤独，那个人一定也怀着满心的期待，拥着一腔孤勇，穿过茫茫人海，也要来与你相见，愿世间美好与你环环相扣...

好吧，这鸡汤我干了。

---

**女朋友的科斯定律**

这个故事是这样的：

有天有个人 A 和一个经济学家叫 Ronald 的吃饭。

 A 很苦恼，饭桌上 A 跟 Ronald 说：我喜欢上一个妹子，她非常优秀，琴棋书画样样精通，还特别好看，可是她已经有男朋友了咋办？

Ronald 说，你还是没那么懂科斯定律啊。

 A 说：？？？

Ronald 说，如果你知道科斯定律，那么就知道，不管这个女孩现在跟谁谈对象，她最后都会跟最匹配她的人在一起的。

 A 说：！！！

Ronald 说，“你激动什么，你不是知道科斯定律吗？**科斯定律就是谁最匹配这个资源的，最终总会归谁所有**。”

经济上，可以简单粗暴总结为：**谁用得最好就归谁，给用得最好的人，有些资源在过程中会贬值，有些则会升值**。

对啊，是你的就是你的，不是你的也强求不来。

> 爱情这个东西，始于颜值，陷于才华，忠于人品，痴于肉体，迷于声音，最后折扣于物质，败于现实，最后归于尘土。

![](https://upload-images.jianshu.io/upload_images/12890819-3660f31da3e82adb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 旅游

今年去了广州极地海洋世界逛了一下

![](https://upload-images.jianshu.io/upload_images/12890819-bd984021eac2c631.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-958f0b626f743107.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-236dd5282d7cc474.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

团建去了清远漂流与轰趴、玩了卡丁车、嗨马乐动

![](https://upload-images.jianshu.io/upload_images/12890819-9248c05cc76b96cd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/12890819-67a068a0917bbd9b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

还是太宅了啊，2021 年，多出去走、多出去走、多出去走。

## 3 年之痒

今年已经是工作的第三年了啊，7 月份的时候，3 年之期到来的时候，真的是非常彷徨，非常迷茫，心态有点不适应。

之所以心态有点不适应，可能就是因为这 3 年的成长不及预期吧，和工作了一两年的时候的感觉完全不同，真的是非常焦虑，非常感慨，原来自己已经毕业 3 年了啊，都成了混社会的老油条了啊。

是啊，谁的青春不迷茫呢，既然迷茫没有方向就专注于做好当下的事情。

可能要渡过迷茫这场大劫，要做些跳出当前舒适圈的事情，和更困难的事情。

![](https://upload-images.jianshu.io/upload_images/12890819-e666be1531751f3a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 总结

总的来说，2020 成长不及预期，收获也不及预期，不由得一声叹息：生活艰难！

---

像我这样迷茫的人

像我这样寻找的人

像我这样碌碌无为的人

你还见过多少人

像我这样不甘平凡的人

世界上有多少人

一首毛不易的《像我这样的人》就是我 2020 年的最真实写照了。

![](https://upload-images.jianshu.io/upload_images/12890819-78234619631eeff4.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 进阶 2021

![](https://upload-images.jianshu.io/upload_images/12890819-669f6d2a0f7f3665.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

2021 目标

- 用 Vue3.0 重构我的开源博客项目
- 继续深入学习 Vue3.0、 TypeScript、Node 技术栈
- 保持运动与健身
- 继续学习理财，入手新股新债
- 坚持写作、开源、24 篇原创技术文章
- 运营好公众号
- 多阅读
- 掌握摄影技术
- 脱单

![](https://upload-images.jianshu.io/upload_images/12890819-5359afb1d980ea6e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

乾坤未定，你我皆黑马。

黑不黑不重要，要得是这么个态度，哼~

## 最后

祝大家新年快乐。

最后，一首林俊杰的《进阶》送给你。

前方被乌云笼罩了

重生的力量来自真我

战胜可敬的对手

坚持信念是我的所有

抵达心中的辽阔

希望听过这首歌的人以及看到这篇文章的人都能 **进阶**，不再迷惘，心灵在进阶之后找到方向。

**愿你尝遍烟火，依然相信，人间值得。**

**乾坤未定，你我皆黑马！**

**对未来还很有信心，我相信我可以。**

**时光正好，未来还有无限可能!**

**2021 我们一起进阶！！！**

![](https://upload-images.jianshu.io/upload_images/12890819-1f25fdfac56d445c.jpeg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by FearwareX** [comment]
阅读完感触很深，感觉比自己强的人都在努力，自己凭什么消磨时间！2021加油！:zap:

**Comment by biaochenxuying** [comment]
> 阅读完感触很深，感觉比自己强的人都在努力，自己凭什么消磨时间！2021加油！⚡

加油！2021 我们一起进阶！！！

**Comment by hjhwel** [comment]
50万

**Comment by j710328466** [comment]
如果有一天我变的很有钱

**Comment by biaochenxuying** [comment]
> 50万

当被动收入能达到 50万，就能财富自由了

**Comment by biaochenxuying** [comment]
> 如果有一天我变的很有钱

当有一天我财富自由了

**Comment by wiredgril666** [comment]
respect,像优秀的人学习~

**Comment by BWmelon** [comment]
哈哈哈，每年的目标都有脱单☺

**Comment by biaochenxuying** [comment]
> 哈哈哈，每年的目标都有脱单☺

扎心了 老铁
